from enum import Enum


class Tags(str, Enum):
    schedules = "schedules"
    asc = "asc"
    auth = "auth"
    periods = "periods"
    job_titles = "job_titles"
    departments = "departments"
    branches = "branches"
    stages = "stages"
    buildings = "buildings"
    rooms = "rooms"
    floors = "floors"
    subjects = "subjects"
    lessons = "lessons"
    cards = "cards"
    days = "days"
    users = "users"
    teachers = "teachers"
    employees = "employees"
    students = "students"
    others = "others"
    roles = "roles"
    models = "models"
