"""role_name

Revision ID: 374bbc1fd31e
Revises: 32b24b4735ca
Create Date: 2022-03-30 21:47:10.571780

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '374bbc1fd31e'
down_revision = '32b24b4735ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'color_light')
    op.drop_column('building', 'color_dark')
    op.add_column('role', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('role', sa.Column('enum', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('role', 'ar_name')
    op.drop_column('role', 'en_name')
    op.drop_column('room', 'color_light')
    op.drop_column('room', 'color_dark')
    op.drop_column('subject', 'color_light')
    op.drop_column('subject', 'color_dark')
    op.drop_index('ix_user_en_name', table_name='user')
    op.drop_column('user', 'color_light')
    op.drop_column('user', 'color_dark')
    op.drop_column('user', 'en_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('en_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('color_dark', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('color_light', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_en_name', 'user', ['en_name'], unique=False)
    op.add_column('subject', sa.Column('color_dark', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('color_light', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('color_dark', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('color_light', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('en_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('ar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('role', 'enum')
    op.drop_column('role', 'name')
    op.add_column('building', sa.Column('color_dark', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('building', sa.Column('color_light', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
