"""add_user_colors

Revision ID: a5e157faf0fc
Revises: b66d32cdc6f3
Create Date: 2022-02-10 16:59:03.945818

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
from bot_app.theme import random_color, random_dark

revision = 'a5e157faf0fc'
down_revision = 'b66d32cdc6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('color_light', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                        server_default=random_color()))
    op.add_column('building', sa.Column('color_dark', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                        server_default=random_dark()))
    op.add_column('room', sa.Column('color_light', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                    server_default=random_color()))
    op.add_column('room', sa.Column('color_dark', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                    server_default=random_dark()))
    op.add_column('subject', sa.Column('color_light', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                       server_default=random_color()))
    op.add_column('subject', sa.Column('color_dark', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                       server_default=random_dark()))
    op.add_column('user', sa.Column('color_light', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                    server_default=random_color()))
    op.add_column('user', sa.Column('color_dark', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                    server_default=random_dark()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'color_dark')
    op.drop_column('user', 'color_light')
    op.drop_column('subject', 'color_dark')
    op.drop_column('subject', 'color_light')
    op.drop_column('room', 'color_dark')
    op.drop_column('room', 'color_light')
    op.drop_column('building', 'color_dark')
    op.drop_column('building', 'color_light')
    # ### end Alembic commands ###
