"""user_model

Revision ID: ee74928015c8
Revises: 374bbc1fd31e
Create Date: 2022-03-31 20:38:33.834409

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee74928015c8'
down_revision = '374bbc1fd31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_building_name', table_name='building')
    op.alter_column('room', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_room_name', table_name='room')
    op.alter_column('stage', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subject', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_subject_name', table_name='subject')
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_user_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_subject_name', 'subject', ['name'], unique=False)
    op.alter_column('subject', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stage', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_room_name', 'room', ['name'], unique=False)
    op.alter_column('room', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_building_name', 'building', ['name'], unique=False)
    op.alter_column('building', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
