"""user_image_rename

Revision ID: f349764591b2
Revises: ee74928015c8
Create Date: 2022-03-31 20:58:58.693905

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f349764591b2'
down_revision = 'ee74928015c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###
